// src/lib/magic-link.ts
//
// Passwordless onboarding entry. A magic link is generated when a client is
// created (and re-generated by the re-engagement cron if they never sign the
// contract). The link is delivered two ways:
//   1. Written to a GHL custom field (env MAGIC_LINK) + a `send-magic-link` tag
//      so a GHL workflow can fire the SMS.
//   2. Embedded in the welcome email (see src/lib/email.ts).
//
// The link logs the client straight into /onboarding via the existing
// /auth/callback PKCE exchange. The client never sees the temporary password
// the auth user was created with — they set their own during onboarding Step 3.

import { createAdminClient } from "@/lib/supabase/admin";
import { ghlUpdateContact, ghlAddTags } from "@/lib/ghl-api";

/**
 * Generates a magic (passwordless) login link that lands the client in the
 * onboarding flow. Returns a link to OUR /auth/confirm route, or null if
 * generation failed.
 *
 * We deliberately do NOT return Supabase's `action_link`. That link points at
 * Supabase's /auth/v1/verify endpoint and, after verifying, redirects to the
 * link's `redirect_to` using the IMPLICIT flow (tokens in a `#hash`). Two
 * problems with that for us:
 *   1. `redirect_to` must be in the project's allowed Redirect URLs or Supabase
 *      silently falls back to the Site URL (prod) — so localhost never works.
 *   2. The hash-token landing doesn't flow through our PKCE `/auth/callback`.
 *
 * Instead we build our own link using `properties.hashed_token` and point it at
 * the SSR `/auth/confirm` route (which calls verifyOtp server-side, sets the
 * session cookie, then redirects to `next`). The domain comes from
 * NEXT_PUBLIC_APP_URL, so it honors localhost in dev with no Supabase config.
 */
export async function generateOnboardingMagicLink(email: string): Promise<string | null> {
  const appUrl = process.env.NEXT_PUBLIC_APP_URL || "https://vault.creditbanc.io";

  try {
    const supabaseAdmin = createAdminClient();
    const { data, error } = await supabaseAdmin.auth.admin.generateLink({
      type: "magiclink",
      email: email.toLowerCase(),
    });

    if (error) {
      console.error("❌ Magic link generation error:", error.message);
      return null;
    }

    const tokenHash = data?.properties?.hashed_token;
    if (!tokenHash) {
      console.error("❌ Magic link generation returned no hashed_token");
      return null;
    }

    const next = encodeURIComponent("/onboarding");
    return `${appUrl}/auth/confirm?token_hash=${tokenHash}&type=magiclink&next=${next}`;
  } catch (err) {
    console.error("❌ Magic link generation threw:", err);
    return null;
  }
}

/**
 * Pushes the magic link to GHL: writes it to the MAGIC_LINK custom field and
 * adds the `send-magic-link` tag so a GHL workflow can dispatch the SMS.
 * Non-fatal — logs and swallows errors so it never breaks the calling flow.
 */
export async function pushMagicLinkToGhl(contactId: string, link: string): Promise<void> {
  const fieldId = process.env.MAGIC_LINK;
  if (!fieldId) {
    console.warn("⚠️ MAGIC_LINK env (GHL custom field id) not set — skipping GHL push");
    return;
  }

  try {
    await ghlUpdateContact(contactId, {
      customFields: [{ id: fieldId, value: link }],
    });
    await ghlAddTags(contactId, ["send-magic-link"]);
    console.log(`✅ Magic link pushed to GHL contact ${contactId} (+ send-magic-link tag)`);
  } catch (err) {
    console.error("⚠️ Failed to push magic link to GHL (non-fatal):", err);
  }
}
